#!/bin/bash
set -euo pipefail

#PBS -N turboprep
#PBS -l walltime=00:05:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=16gb
#PBS -o ../logs/turboprep_$PBS_JOBID.out
#PBS -e ../logs/turboprep_$PBS_JOBID.err
#PBS -m ae
#PBS -M pierre.falconnier@creatis.insa-lyon.fr


# by default on clreatis cluster, the job starts in the home directory
# cd "$PBS_O_WORKDIR" # where the qsub ticket was submitted from
# cd Documents/mri-preprocessing/


$HOME/Documents/mri-preprocessing/.venv/bin/python $HOME/Documents/mri-preprocessing/preprocessing/turboprep-multiple-v2.py \
  --inputs  "$TEMP_DIR/inputs_chunk_${SUF}" \
  --outputs "$TEMP_DIR/outputs_chunk_${SUF}" \
  --template MNI_templates/MNI152_T1_1mm_brain.nii.gz \
  --threads "$PBS_NP"
