# !/bin/bash

echo "PBS script started"


# set -euo pipefail

#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=2
#PBS -l mem=32gb
#PBS -m ae
#PBS -M pierre.falconnier@creatis.insa-lyon.fr

# by default, the job starts in the home directory
# cd "$PBS_O_WORKDIR" # where the qsub ticket was submitted from

# Navigate to the project directory
cd "$HOME/Documents/mri-preprocessing/"
# source .venv/bin/activate
export PYTHONUNBUFFERED=1
# export HYDRA_FULL_ERROR=1

# Run the pipeline using the variables passed via qsub -v
uv run python $HOME/Documents/mri-preprocessing/preprocessing/turboprep-multiple-v2.py \
  --inputs "$IN_FILE" \
  --outputs "$OUT_FILE" \
  --template $HOME/Documents/mri-preprocessing/MNI_templates/MNI152_T1_1mm_brain.nii.gz \
  --threads "$PBS_NP"